name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Change to source code directory
        run: cd sunghwa1004/sungact/blob/main

      - name: Build and deploy
        run: |
          npm install
          npm run build
          mkdir public
          cp -r build/* public/
          echo "${{ secrets.MY_GITHUB_TOKEN }}" > public/.token
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add public
          git commit -m "Deploy"
          git push
